### ISSUE TITLE
Contribute to workflowr package for reproducible data analysis

### ISSUE THREAD

**Issue by jdblischak** [chirunconf/chirunconf19#14]
Hi all! I'm the author of the CRAN package [workflowr](https://github.com/jdblischak/workflowr). It combines literate programming (knitr and rmarkdown) and version control (Git, via git2r) to generate a website containing time-stamped, versioned, and documented results. Some examples of workflowr projects include [fibroblast-clonality](https://davismcc.github.io/fibroblast-clonality/), [rccSims](https://jean997.github.io/rccSims/), [truncash](https://lsun.github.io/truncash/), and [threeprimeseq](https://brimittleman.github.io/threeprimeseq/) (this last one has been updated with the most recent release).

I'm excited to help mentor new open source contributors, and I've tagged some Issues with the label [Chicago R Unconference](https://github.com/jdblischak/workflowr/issues?q=is%3Aissue+is%3Aopen+label%3A%22Chicago+R+Unconference%22). They range in time commitment from minimal (adding a safety check to warn a user about a potential issue) to more involved (a Shiny Gadget/RStudio Addin). I use testthat for testing my package, so if you're interested in learning more about how to do that, the safety check for a pandoc installation would be a good option.

- [ ] Fail early if user tries to use SSH but SSH is not enabled https://github.com/jdblischak/workflowr/issues/144
- [x] Fail early if pandoc is not installed https://github.com/jdblischak/workflowr/issues/75
- [ ] Allow user to add commit message interactively https://github.com/jdblischak/workflowr/issues/33
- [x] Create interactive RStudio Addin (Shiny Gadget) for `wflow_publish()` https://github.com/jdblischak/workflowr/issues/143

**Comment by alexpghayes** [comment]
Would you mind giving a brief explanation of what literate programming and version control are for people who might not have heard those terms before?

**Comment by jdblischak** [comment]
**literate programming** - mixing code, text, and results in the same file
  * Resources:
    * [Data Carpentry - Reproducible Research Literate Programming](https://datacarpentry.org/rr-literate-programming/)
    * [R Markdown documentation](https://rmarkdown.rstudio.com/)

**version control** - saving snapshots of documents as they change over time with very fine-grained control (which facilitates experimentation and collaboration)
  * Resources:
    * [Version control on Wikipedia](https://en.wikipedia.org/wiki/Version_control)
    * [Happy Git and GitHub for the useR](https://github.com/jennybc/happy-git-and-github-for-the-user)
    * [Software Carpentry Git lesson](https://swcarpentry.github.io/git-novice/)
    * [A Quick Introduction to Version Control with Git and GitHub](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004668)

**Comment by jdblischak** [comment]
@zaynaib addressed Issue jdblischak/workflowr#75 with PR https://github.com/jdblischak/workflowr/pull/146!

**Comment by jdblischak** [comment]
@zaynaib and @argdata addressed Issue jdblischak/workflowr#143 with PR jdblischak/workflowr#147!
